[package]
name = "event_source"
version = "0.1.0"
authors = ["Duane Bailey <bailey.d.r@gmail.com>"]

[dependencies]
serde = "*"
serde_json = "1.0"
serde_derive = "*"
either = "*"
dotenv = "*"
warp = "*"
futures = "*"
log = "*"
chashmap = "*"
pretty_env_logger = "*"
tokio-timer = "*"
hyper = "*"

[dependencies.chrono]
version = "*"
features = ["serde"]

[dependencies.uuid]
version = "*"
features = ["v4", "serde"]

[dependencies.rusqlite]
version = "*"
features = ["bundled", "chrono", "serde_json", "trace"]